### Compose structure for Vapor development and testing ###
# TODO: Get rid of this entirely. Run it explicitly for testing,
# but otherwise we should only use one compose file.
services:
  # Neo4j GraphDB 
  neo4j-dev:
    image: neo4j:2025.05.0
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PW}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted="apoc.text.*"
    # Map to different ports than the production service
    # NOTE: This does create an issue of the user needing to specify 
    # NEO4J_URI=neo4j://localhost:7688 (instead of 7687) and there is
    # not a convenient way to flip back and forth without creating an
    # additional dev.env file and specifying that in the entire dev structure.
    # See todo at the top.
    ports:
      - 7474:7474
      - 7687:7687
    # Rename the network so it doesn't conflict with production service
    networks:
      - dev

  mcp-dev:
    image: vapor-mcp:latest
    volumes:
      - ./.env:/app/.env
    ports:
      - 8000:8000
    command: fastmcp run vapor/svc/mcp/run.py:mcp --transport http --port 8000
    depends_on:
      - neo4j-dev
    networks:
      - dev

networks:
  dev: 
    driver: bridge
    