### Compose structure for Vapor development and testing ###
services:
  # Neo4j GraphDB 
  neo4j:
    image: neo4j:2025.05.0
    environment:
      - NEO4J_AUTH=neo4j/neo4j-dev
    # Map to different ports than the production service
    ports:
      - 7475:7474
      - 7688:7687
    