### Compose structure for Vapor development and testing ###
services:
  # Neo4j GraphDB 
  neo4j-dev:
    image: neo4j:2025.05.0
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PW}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted="apoc.text.*"
    # Map to different ports than the production service
    ports:
      - 7475:7474
      - 7688:7687
    # Rename the network so it doesn't conflict with production service
    networks:
      dev: {}

networks:
  dev: {}
    